language: r
dist: trusty
sudo: required

branches:
  only:
    - master

cache:
  packages: yes
  directories:
    - $HOME/bin

install:
  - ./install_dependencies.sh

script:
  - Rscript deploy.R

deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  on:
    branch: master
  local_dir: public
  target_branch: gh-pages
